### ISSUE TITLE
Third-level parenthesis/brackets are very dark

### ISSUE THREAD

**Issue by mrmckeb** [franzgollhammer/jb-fleet-dark#1]
Hi there, I was trying out your theme and noticed that parenthesis/brackets can become very dark at what appears to be at the third-level. Is this something you can tweak/change?
<img width="254" alt="image" src="https://github.com/franzgollhammer/jb-fleet-dark/assets/5043083/8c8eaa10-4849-4a9c-8b03-f5357a815214">

This was in JavaScript/TypeScript, with "Fleet Dark" (not flat).

**Comment by franzgollhammer** [comment]
@mrmckeb thanks for reporting. Should be fixed in the latest version. 👍
